In [2]:
from KeemPlot import *
import pandas as pd

In [3]:
path = "/Volumes/BIG_DATA/04_DATA/04_LIVE_BACTERIAL_IMAGING_ANALYSIS/bactoquant/REP1/"
dir1 = KeemPlot(path + "JUB66_RFP/", 1, 65535, 0, 3500)
dir2 = KeemPlot(path + "JUB66_RFP_IN_CEMBIO", 2, 65535, 0, 3500)
dir3 = KeemPlot(path + "MK_JUB66_RFP_IN_JUB66", 1, 65535, 0, 3500)

In [4]:
dir1.flatdata_ut[0].shape

(3500,)

In [5]:
dir1.flatdata_ni[0].shape

(2457,)

In [6]:
dir1.generate_db()
dir2.generate_db()
dir3.generate_db()

In [7]:
dir1.update_db("/Users/amoore/projects/stable_txts/IMDB.pkl")
dir2.update_db("/Users/amoore/projects/stable_txts/IMDB.pkl")
dir3.update_db("/Users/amoore/projects/stable_txts/IMDB.pkl")

In [3]:
tmp = pd.read_pickle("/Users/amoore/projects/stable_txts/IMDB.pkl")

In [10]:
tmp.reset_index(inplace=True, drop=True)

In [4]:
tmp

,date,strain,feed,temp,name,stage,rating,comments,ID,array_vals,array_vals_ni
0,230614,N2,JUB66_RFP,25,image1,YL4,4,comments,00021,"[0.011764705882352941, 0.011764705882352941, 0...","[0.011764705882352941, 0.011764705882352941, 0..."
1,230614,N2,JUB66_RFP,25,image2,YL4,4,comments,00022,"[0.010910200656137941, 0.01151731697290573, 0....","[0.010910200656137941, 0.011764705882352941, 0..."
2,230614,N2,JUB66_RFP,25,image3,YL4,5,comments,00023,"[0.011764705882352941, 0.011764705882352941, 0...","[0.011764705882352941, 0.011764705882352941, 0..."
3,230614,N2,JUB66_RFP,25,image4,YL4,4,comments,00024,"[0.011444266422522316, 0.011697760685114819, 0...","[0.011444266422522316, 0.011764705882352941, 0..."
4,230614,N2,JUB66_RFP,25,image5,YL4,4,Lots of signal in this one all concentrated n...,00025,"[0.011764705882352941, 0.014485120414898868, 0...","[0.011764705882352941, 0.015030136568245976, 0..."
...,...,...,...,...,...,...,...,...,...,...,...
85,230721,N2,MK_JUB66_RFP_IN_JUB66,25,image6,L4,4,comments,00106,"[0.011764705882352941, 0.011764705882352941, 0...","[0.011764705882352941, 0.011764705882352941, 0..."
86,230721,N2,MK_JUB66_RFP_IN_JUB66,25,image7,YL4,4,comments,00107,"[0.011764705882352941, 0.011764705882352941, 0...","[0.011764705882352941, 0.011764705882352941, 0..."
87,230721,N2,MK_JUB66_RFP_IN_JUB66,25,image8,L4,3,comments,00108,"[0.011764705882352941, 0.011764705882352941, 0...","[0.011764705882352941, 0.011764705882352941, 0..."
88,230721,N2,MK_JUB66_RFP_IN_JUB66,25,image9,L4,4,comments,00109,"[0.011764705882352941, 0.011764705882352941, 0...","[0.011764705882352941, 0.011764705882352941, 0..."
89,230721,N2,MK_JUB66_RFP_IN_JUB66,25,image10,L4,3,comments,00110,"[0.011764705882352941, 0.011764705882352941, 0...","[0.011764705882352941, 0.011764705882352941, 0..."

In [14]:
dir1.update_db("/Volumes/onishlab_shared/PROJECTS/30_Andrew/03_IMAGING_DATABASE/IMDB.pkl")
dir2.update_db("/Volumes/onishlab_shared/PROJECTS/30_Andrew/03_IMAGING_DATABASE/IMDB.pkl")
dir3.update_db("/Volumes/onishlab_shared/PROJECTS/30_Andrew/03_IMAGING_DATABASE/IMDB.pkl")

In [5]:
tmp = pd.read_pickle("/Volumes/onishlab_shared/PROJECTS/30_Andrew/03_IMAGING_DATABASE/IMDB.pkl")

In [12]:
columns = list(tmp.columns)

In [13]:
columns[2] = "diet"

In [15]:
columns = np.array(columns)

In [17]:
tmp.columns = columns

,date,strain,diet,temp,name,stage,rating,comments,ID,array_vals,array_vals_ni,REP
0,230614,N2,JUB66_RFP,25,image1,YL4,4,comments,00021,"[0.011764705882352941, 0.011764705882352941, 0...","[0.011764705882352941, 0.011764705882352941, 0...",1
1,230614,N2,JUB66_RFP,25,image2,YL4,4,comments,00022,"[0.010910200656137941, 0.01151731697290573, 0....","[0.010910200656137941, 0.011764705882352941, 0...",1
2,230614,N2,JUB66_RFP,25,image3,YL4,5,comments,00023,"[0.011764705882352941, 0.011764705882352941, 0...","[0.011764705882352941, 0.011764705882352941, 0...",1
3,230614,N2,JUB66_RFP,25,image4,YL4,4,comments,00024,"[0.011444266422522316, 0.011697760685114819, 0...","[0.011444266422522316, 0.011764705882352941, 0...",1
4,230614,N2,JUB66_RFP,25,image5,YL4,4,Lots of signal in this one all concentrated n...,00025,"[0.011764705882352941, 0.014485120414898868, 0...","[0.011764705882352941, 0.015030136568245976, 0...",1
...,...,...,...,...,...,...,...,...,...,...,...,...
85,230721,N2,MK_JUB66_RFP_IN_JUB66,25,image6,L4,4,comments,00106,"[0.011764705882352941, 0.011764705882352941, 0...","[0.011764705882352941, 0.011764705882352941, 0...",3
86,230721,N2,MK_JUB66_RFP_IN_JUB66,25,image7,YL4,4,comments,00107,"[0.011764705882352941, 0.011764705882352941, 0...","[0.011764705882352941, 0.011764705882352941, 0...",3
87,230721,N2,MK_JUB66_RFP_IN_JUB66,25,image8,L4,3,comments,00108,"[0.011764705882352941, 0.011764705882352941, 0...","[0.011764705882352941, 0.011764705882352941, 0...",3
88,230721,N2,MK_JUB66_RFP_IN_JUB66,25,image9,L4,4,comments,00109,"[0.011764705882352941, 0.011764705882352941, 0...","[0.011764705882352941, 0.011764705882352941, 0...",3
89,230721,N2,MK_JUB66_RFP_IN_JUB66,25,image10,L4,3,comments,00110,"[0.011764705882352941, 0.011764705882352941, 0...","[0.011764705882352941, 0.011764705882352941, 0...",3